data:
  folder_path: 'data/UTKFace'
  target_size: [200, 200]
  batch_size: 32

model:
  input_shape: [200, 200, 3]
  vgg16_include_top: False
  dense_units: 512
  activation: 'relu'

training:
  epochs: 10
  optimizer: 'adamW'
  loss:
    age: 'mse'
    gender: 'binary_crossentropy'
  metrics:
    age: 'mse'
    gender: 'accuracy'